apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: cool-app
  name: cool-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cool-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cool-app
    spec:
      containers:
      - image: ciberkleid/cool-app
        name: cool-app
        resources: {}
status: {}
