apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: sample-app-nodejs
  name: sample-app-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sample-app-nodejs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: sample-app-nodejs
    spec:
      containers:
      - image: ciberkleid/sample-app-nodejs:latest
        name: sample-app-nodejs
        resources: {}
status: {}
